'use client'
import Image from 'next/image'
import { IoSearch } from "react-icons/io5";
import { FaRegUser } from "react-icons/fa6";

import Link from 'next/link'
import React from 'react'
import { usePathname } from 'next/navigation';

export const metadata = {
  title: "Distict by Zomato",
  description: "Generated by create next app",
};

const Navbar = () => {

    const pathname = usePathname();

    const navLinkClass = (path)=>`font-semibold rounded-2xl px-4 py-1 transition
     ${ pathname === path
         ? 'bg-violet-500 text-white'
         : 'text-gray-700'
     }`

  return (
    <div className='bg-white z-50 shadow items-center flex p-4 text-black justify-between min-w-2xl sticky top-0'> 
    <div>
         <Image
          className="dark:invert ml-4 "
          src="/logo.svg"
          alt="Next.js logo"
          width={110}
          height={20}
          priority
          />
          </div>       

        <div className='items-center flex text-center justify-around'>
         <ul className='flex gap-10 '>

        <li className={navLinkClass('/')}>
          <Link href="/">For you</Link>
        </li>
        
        <li className={navLinkClass('/events')}>
          <Link href="/events">Events</Link>
        </li>

        <li className={navLinkClass('/booking')}>
          <Link href="/booking">Booking</Link>
        </li>

        <li className={navLinkClass('/checkout')}>
          <Link href="/checkout">Checkout</Link>
        </li>
            </ul>
        </div>

        <div className='flex gap-10 items-center '>
            <IoSearch className='w-6 h-6 text-purple-500' />
            <p className='bg-gray-400 w-12 h-12 rounded-full relative flex items-center justify-center'><FaRegUser className='w-4 h-4 text-gray-200' /></p>
        </div>
      
    </div>
  )
}

export default Navbar
